#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/rustdesk-lan/rustdesk-lan /usr/bin/rustdesk-lan

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/rustdesk-lan.service ]; then
			rm -f /etc/systemd/system/rustdesk-lan.service /usr/lib/systemd/system/rustdesk-lan.service /usr/lib/systemd/user/rustdesk-lan.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/rustdesk-lan/files/systemd/rustdesk-lan.service /usr/lib/systemd/system/rustdesk-lan.service
		# try fix error in Ubuntu 18.04
		# Failed to reload rustdesk.service: Unit rustdesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/rustdesk.service:10: Executable path is not absolute: pkill -f "rustdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/rustdesk-lan.service
		fi
		systemctl daemon-reload
		systemctl enable rustdesk-lan
		systemctl start rustdesk-lan
	fi
fi
